# -*- coding: utf-8 -*-
"""Lesson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUgTuI3Inf0nrVRPakfgkAiWzT2hRNUY
"""

import numpy as np
import random as rnd
import random
import matplotlib.pyplot as plt

interval = (-10,10)
def f(x):
  return x*x+2*x-5

def cost_function(x):
  return f(x)

def random_start():
  a,b = interval
  return random.uniform(a,b)

def temperature(fraction):
  return max(0.01, min(1,1-fraction))

def clip(x):
  a,b = interval
  return max(min(x,b),a)      # x eğer -10 ile +10 arasında gelmezse clip etmek istiyoruz

def random_komsu(state, fraction):
  genlik = (max(interval)-min(interval)) * fraction / 10
  delta = (-genlik/2) + genlik * random.random()
  return clip(state+delta)

def kabul_olasiligi(cost, new_cost, T):
  if(new_cost < cost):
    return 1
  else:
    p = np.exp(-(new_cost-cost)/T)
    return p

iterasyon = 1000
debug = True
state= random_start()
cost=cost_function(state)
states, costs = [state],[cost]

best_state = state

for step in range(iterasyon):
  fraction = step/float(iterasyon)
  T = temperature(fraction)
  new_state = random_komsu(state, fraction)
  new_cost = cost_function(new_state)
  if debug:
    print("Step: ", step, "/", iterasyon )
    print("State:", state, " Cost: ", cost)
    print("New State: ", new_state, "New Cost: ", new_cost)
    print("T:", T)
  if(new_cost <= cost):
    state, cost = new_state, new_cost
    states.append(state)
    costs.append(cost)
  elif kabul_olasiligi(cost, new_cost, T) > rnd.random():
    state, cost = new_state, new_cost
    states.append(state)
    costs.append(cost)
print(state, cost)

plt.figure()
plt.subplot(121)
plt.plot(states, 'r')
plt.title("States")
plt.subplot(122)
plt.plot(costs, "b")
plt.title("Costs")